# the source tree needs to be "booted" for this stack.yaml file to be usable:
#
# $ git submodule update --init --recursive
# $ (cd ghc && ./boot && ./make)
# $ ./utils/makePackages.sh
#

resolver: lts-11.20
packages:
  - .
  - ./lib/ghc-api-ghcjs
  - ./lib/ghci-ghcjs
  - ./lib/ghcjs-th
  - ./lib/haddock-api-ghcjs
  - ./lib/haddock-library-ghcjs
  - ./lib/template-haskell-ghcjs

extra-deps:
  - haskell-src-exts-1.18.2
